version: '3.7'
services:
  web:
    build: .
    command: start_db
    ports:
      - 80:8080
    links:
      - db
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mYstr0ngPa$$w0rd
      MYSQL_HOST: db

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: r00T-mYstr0ngPa$$w0rd
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: mYstr0ngPa$$w0rd
